# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
# Adapted from https://github.com/NeuralEnsemble/python-neo
version: 3
workflows:
  version: 3
  test:
    jobs:
      - test-3.10
jobs:
  test-3.10:
    docker:
      - image: circleci/python:3.10

    working_directory: ~/repo

    steps:
      - checkout
      - run: sudo chown -R circleci:circleci /usr/local/bin

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-py3-dependencies-{{ checksum "requirements.txt" }}
            # fallback to using the latest cache if no exact match is found
            - v1-py3-dependencies-

      - run:
          name: Install git-lfs
          command: |
            sudo apt-get install git-lfs
            git lfs install

      - run:
          name: install dependencies
          command: |
            python -m venv venv
            . venv/bin/activate
            pip install --upgrade pip
            pip install -r requirements.txt
            pip install pytest
            pip install pytest-cov


      - save_cache:
          paths:
            - ./venv
          key: v1-py3-dependencies-{{ checksum "requirements.txt" }}


      # run tests!
      - run:
          name: run tests
          no_output_timeout: 30m
          command: |
            . venv/bin/activate
            pytest --ignore=tdc/test/dev_tests/ --ignore=tdc/test/test_resources.py --ignore=tdc/test/test_dataloaders.py

      - store_artifacts:
          path: test-reports
          destination: test-reports
